# Generated by Django 5.2.7 on 2025-10-13 09:58

from django.db import migrations

def copy_old_data_to_new_table(apps, schema_editor):
    """
    Copy data from the old Address and Letting models in 'oc_lettings_site'
    to the new Address and Letting models in the 'lettings' app.

    This function preserves the relationship between lettings and addresses
    by using a mapping dictionary from old address IDs to new Address instances.
    """
    # Récupère anciens modèles Address et Letting dans l'app oc_lettings_site
    OldAddressModel = apps.get_model('oc_lettings_site', 'Address')
    OldLettingModel = apps.get_model('oc_lettings_site', 'Letting')

    # Récupère les nouveaux modèles dans l'app lettings
    NewAddressModel = apps.get_model('lettings', 'Address')
    NewLettingModel = apps.get_model('lettings', 'Letting')

    # Dictionnaire pour relier les anciennes adresses aux nouvelles
    address_map = {}

    # Copie des addresses
    for old in OldAddressModel.objects.all():
        new_addr = NewAddressModel.objects.create(
            number=old.number,
            street=old.street,
            city=old.city,
            state=old.state,
            zip_code=old.zip_code,
            country_iso_code=old.country_iso_code,
        )
        # Correspondance entre l'id de l'ancien avec l'addresse du nouveau
        address_map[old.id] = new_addr

    # Copie des lettings
    for old in OldLettingModel.objects.all():
        # Récupérer dans dictionnaire nouvelle addresse de l'ancien id
        new_address = address_map.get(old.address_id)
        if new_address:
            NewLettingModel.objects.create(
                title=old.title,
                address=new_address,
            )


def reverse_copy_data(apps, schema_editor):
    """
    Reverse the copy_old_data_to_new_table operation by deleting
    all entries in the new Address and Letting models in 'lettings'.
    """
    NewAddressModel = apps.get_model('lettings', 'Address')
    NewAddressModel.objects.all().delete()
    NewLettingModel = apps.get_model('lettings','Letting')
    NewLettingModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_old_data_to_new_table, reverse_copy_data),
    ]
