# Generated by Django 5.2.7 on 2025-10-13 09:58

from django.db import migrations

def copy_old_data_to_new_table(apps, schema_editor):
    # Récupère les modèles à partir du "registry" des migrations
    OldModel = apps.get_model('oc_lettings_site', 'Address')
    NewModel = apps.get_model('lettings', 'Address')

    for old in OldModel.objects.all():
        NewModel.objects.create(
            number=old.number,
            street=old.street,
            city=old.city,
            state=old.state,
            zip_code=old.zip_code,
            country_iso_code=old.country_iso_code,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_old_data_to_new_table),
    ]
